sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth active-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-production-298412
  - gcloud config set compute/zone europe-west1-d
  - gcloud container clusters get-credentials multi-k8s-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t nhukangasniemi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nhukangasniemi/react-test npm test